### ISSUE TITLE
Window "resize"

### ISSUE THREAD

**Issue by BasilisXs** [angelsix/fasetto-word#9] opened 2017-08-09 17:17 UTC
im not sure if i should compare your application with a normal windows one but there is another one issue:
when you grab and drug the bottom or the top edge and hit to the top-bot side the  new size of the windows is not correct, there is a gap from the top side of windows and the really top of the screen.
Also i know that is not the right place to do questions but i couldn't find better. So i apologize if you already explained it at your videos but my question is: Why you have this hook at "Fasseto.Word\Window\WindowsResizer.cs" Line:268 

                case 0x0024:/* WM_GETMINMAXINFO */

while this case is there at 0024 the application window cant resize the height and the width more than the main monitor dimensions. You need that for some reason ? a Windows app like Paint for example can get the height and the width of the virtual monitor. At this case if you relapse the 0024 with 0000 for example everything seems to work perfectly, except the fact that you can use all monitors now.
thank you in advance

**Comment by angelsix** [comment] 2017-08-09 17:30
I don't get that issue. I drag the window to the very top and the window docks top and bottom and removes the border.

I drag it close to top and then close to bottom and same thing, I get perfect top to bottom fill

![screenshot_1](https://user-images.githubusercontent.com/4455939/29135054-c008acd0-7d30-11e7-8611-a75fa041fde8.png)

For 0024 that is because we are intercepting the entire message pump. We only want to update the window size when the system requests it via a message type of WM_GETMINMAXINFO.

**Comment by BasilisXs** [comment] 2017-08-09 17:39
hmm. in my case i get this no mater the monitor (tested with 2 monitor extended layout & single monitor)

**Comment by BasilisXs** [comment] 2017-08-09 17:47
with a very quick fix-change to do the 0024 0000 you can use the full size of your workstation like this:
![dothis](https://user-images.githubusercontent.com/29635089/29135789-fc862bde-7d43-11e7-99dd-c354ddfe72df.png)

**Comment by angelsix** [comment] 2017-08-09 21:36
Ok you are really making me work for this aren't you. Determined to not be beaten, I dare you to break the code now :+1:

https://github.com/angelsix/fasetto-word/commit/df7986e278633c4711a473bdf81adc231632107d

Please test, confirm and I can close this bug.

PS. There are now no limitations, workarounds or tweaks, this window will behave just like standard windows, even the max size

**Comment by BasilisXs** [comment] 2017-08-10 19:30
ow that is a lot of changes.. for more bugs!! 
i cant wait for the database functionality :D
and no no we dont push you to work on this! see? i gave you 1 day off till to "confirm" 
so:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29635089/29188282-55bb558a-7e1b-11e7-935d-92a7e72cfbc4.gif)

take your time! its your unprofitable project!
im just letting you know things i noticed
Good Luck!

**Comment by angelsix** [comment] 2017-08-10 20:00
I don't see any bug in that animation? The border removing and going to flat when near corners is by design if that's what you mean?

**Comment by BasilisXs** [comment] 2017-08-10 20:04
yes, and ok if you want this. just looks like strange. anyway.
the other thing you see at the gif is that if you dork the window at top there is a not normal gap too

**Comment by angelsix** [comment] 2017-08-10 20:30
Docking just at the top we keep the border and drop Shadow. I can change it so it goes borderless if even one corner goes to an edge? So it looks the same as when in a corner? 

I'll play with it tomorrow if I get time before I go away see if I can come up with a natural solution

**Comment by BasilisXs** [comment] 2017-08-10 21:59
no no, i dont think the problem is that is borderless or not.
the whole window likes to operate normally at this case (when you dock it on top edge).
i thing the issue is that there is a huge gap from the white side of the window that you can see and the real size of the window that is transparent.
![gap](https://user-images.githubusercontent.com/29635089/29193975-4178671a-7e30-11e7-8831-d6c5e23c01ff.PNG)
![redgap](https://user-images.githubusercontent.com/29635089/29193974-4174925c-7e30-11e7-87db-9a94a6c07397.png)

**Comment by angelsix** [comment] 2017-08-11 08:12
Yes that is the part I am talking about. The window itself includes that transparent area for the drop shadow we make around the window. So technically that is the windows edge. Hence why docking docks there.

We are smart about when we remove that border, and by default we remove the rounded edges too. 

Anyway, it clearly looks a bit odd... so I fixed them both. 

Test and confirm please: https://github.com/angelsix/fasetto-word/commit/d8576a70d044a77029ff6cbd68759aa79990f09a

**Comment by BasilisXs** [comment] 2017-08-11 08:26
All fine and smooth!
now you can lock it once for ever :)

**Comment by angelsix** [comment] 2017-08-11 15:52
Cool

**Closed by angelsix** 2017-08-11 15:52 UTC
Labels: bug, testing
